### ISSUE TITLE
似乎有点BUG

### ISSUE THREAD

**Issue by Suz1e** [alex3236/pay#4]
我把源码原封不动的上传进去，但是扫码的时候一直转圈，后续我设置了支付宝收款码url，也上传了小程序赞赏码，但还是转圈

**Comment by alex3236** [comment]
![image](https://user-images.githubusercontent.com/45303195/223063899-8d86e9b9-e50d-4ea5-a622-c6b5cf819e3c.png)
控制台日志截个图

**Comment by Suz1e** [comment]
1：微信扫码后无法显示，文件已经上传
![IMG_2935](https://user-images.githubusercontent.com/52779408/223071787-78dbffb6-9720-4865-987f-ff3b59060e27.PNG)
2：点击使用其他方式付款之后再点回使用微信付款，就只显示一个框了，应该跟问题1一样
![IMG_2936](https://user-images.githubusercontent.com/52779408/223072347-1400c526-bff6-4739-8e54-c36660c2555b.PNG)

控制台

![QQ截图20230306173521](https://user-images.githubusercontent.com/52779408/223072435-683566dc-cd51-4054-9aeb-df54c2489b75.png)

**Comment by Suz1e** [comment]
微信赞赏码用的就是原文件
![QQ截图20230306173410](https://user-images.githubusercontent.com/52779408/223073707-024dd0a7-6d71-4599-a4e3-44e82ce65403.png)

**Comment by Suz1e** [comment]
help me

**Comment by LHXCxyw** [comment]
同问

**Comment by sherrys7** [comment]
QQ扫的时候显示蓝色，微信刚扫会有掉图，刷新几下会出来😣

**Comment by alex3236** [comment]
> 我把源码原封不动的上传进去，但是扫码的时候一直转圈，后续我设置了支付宝收款码url，也上传了小程序赞赏码，但还是转圈

CORS 问题，与项目无关

> QQ扫的时候显示蓝色，微信刚扫会有掉图，刷新几下会出来😣

已修复。
